import Hero from "@/Components/Hero";
import { PropertyGrid } from "@/Components/PropertyGrid";
import connectDB from "@/lib/mongodb";
import Property from "@/models/Property";
import SiteSettings from "@/models/SiteSettings";
import Link from "next/link";

export const dynamic = "force-dynamic";
export default async function HomePage() {
 let settings={}; let properties=[];
 try { await connectDB(); const [s,p]=await Promise.all([SiteSettings.findOne({key:"global"}).lean(),Property.find({status:"Published"}).sort({featured:-1,updatedAt:-1}).limit(6).lean()]); settings=s||{};properties=JSON.parse(JSON.stringify(p)); } catch {}
 return <><Hero settings={settings}/><section className="bg-white py-20 md:py-28"><div className="container-butterfly"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-indigo-700">Handpicked for you</p><h2 className="mt-3 font-display text-4xl text-[#151a3a] md:text-5xl">Find your next <span className="gradient-text">chapter.</span></h2><p className="mt-3 max-w-xl text-slate-500">Explore homes, investment opportunities and commercial spaces selected around your needs.</p></div><Link href="/properties" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-semibold hover:border-indigo-400">View all properties ↗</Link></div><PropertyGrid items={properties}/></div></section><section className="bg-[#f6f8fc] py-20"><div className="container-butterfly grid gap-10 md:grid-cols-2 md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-indigo-700">Beyond four walls</p><h2 className="mt-3 font-display text-4xl leading-tight text-[#151a3a] md:text-5xl">The right space changes everything.</h2><p className="mt-5 leading-7 text-slate-600">Whether you’re buying your first home, exploring resale, looking for land or planning your business premises, we help make the next step clearer.</p><Link href="/about" className="mt-7 inline-flex rounded-full bg-[#151a3a] px-6 py-3.5 text-sm font-semibold text-white">Discover Butterfly Homes ↗</Link></div><div className="grid grid-cols-2 gap-3">{[{t:"Buy a home",h:"/properties"},{t:"Rent a property",h:"/rent"},{t:"Resale homes",h:"/resale"},{t:"Commercial spaces",h:"/commercial"},{t:"New projects",h:"/new-properties"},{t:"Land & plots",h:"/land"}].map(x=><Link key={x.t} href={x.h} className="rounded-2xl border border-white bg-white p-5 font-medium text-[#151a3a] shadow-sm transition hover:-translate-y-1 hover:shadow-md">{x.t}<span className="mt-5 block text-xl text-indigo-700">↗</span></Link>)}</div></div></section><section className="bg-[#151a3a] py-16 text-white"><div className="container-butterfly flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-teal-300">A good move starts here</p><h2 className="mt-3 font-display text-3xl md:text-4xl">Tell us what you’re looking for.</h2></div><Link href="/contact" className="rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#151a3a]">Talk to our team ↗</Link></div></section></>;
}
