"use client";
import Link from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";
import { ArrowUpRight, MapPin, Search } from "lucide-react";
export default function Hero({ settings = {} }) {
  const title = settings.heroTitle || "Find a place that feels like home.";
  const description = settings.heroDescription || "Discover thoughtfully designed homes, premium residences and exceptional spaces created for the way you want to live.";
  const image = settings.heroImage || "/hero-home.jpg";
  return <section className="relative isolate flex min-h-[780px] items-center overflow-hidden bg-[#f9fbfd] pt-24 md:min-h-[850px]"><div className="absolute inset-0 -z-20"><Image src={image} alt="A beautiful home selected by Butterfly Homes" fill priority sizes="100vw" unoptimized className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/90 to-white/25"/><div className="absolute inset-0 bg-gradient-to-t from-[#f9fbfd] via-transparent to-white/20"/></div><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="container-butterfly relative z-10 py-20"><div className="max-w-3xl"><div className="mb-7 flex items-center gap-3"><span className="h-px w-10 bg-gradient-to-r from-[#66D4C8] to-[#7A4CC2]"/><span className="text-xs font-semibold uppercase tracking-[.3em] text-[#3C4592]">A more personal property journey</span></div><h1 className="font-display max-w-3xl text-5xl leading-[1.04] tracking-[-.045em] text-[#151A3A] sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-7 max-w-xl text-base leading-8 text-[#687086] md:text-lg">{description}</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/properties" className="group inline-flex items-center gap-3 rounded-full bg-[#151A3A] px-6 py-4 text-sm font-semibold text-white transition hover:bg-[#3C4592]">Explore properties <ArrowUpRight size={17} className="transition group-hover:translate-x-1 group-hover:-translate-y-1"/></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-[#151A3A]/15 bg-white/80 px-6 py-4 text-sm font-semibold text-[#151A3A] backdrop-blur">Talk to an expert</Link></div><div className="mt-14 grid max-w-xl grid-cols-3 gap-5 border-t border-[#151A3A]/10 pt-6"><div><p className="font-display text-2xl text-[#151A3A]">Homes</p><p className="mt-1 text-xs text-slate-500">For every chapter</p></div><div><p className="font-display text-2xl text-[#151A3A]">Land</p><p className="mt-1 text-xs text-slate-500">Room to grow</p></div><div><p className="font-display text-2xl text-[#151A3A]">Business</p><p className="mt-1 text-xs text-slate-500">Spaces that work</p></div></div></div></motion.div><div className="pointer-events-none absolute bottom-10 right-10 hidden rounded-2xl border border-white/70 bg-white/70 p-4 text-sm text-[#151A3A] shadow-lg backdrop-blur md:block"><div className="flex items-center gap-2"><MapPin size={16} className="text-[#3C4592]"/> Find your place, your way</div></div></section>;
}
