"use client";
import { useState } from "react";
import { ImagePlus, Trash2, Video, FileText, Upload } from "lucide-react";
export default function PropertyMediaManager({value=[],onChange}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function upload(e){const files=[...e.target.files];if(!files.length)return;setBusy(true);setError("");try{const fd=new FormData();files.forEach(f=>fd.append("files",f));const r=await fetch("/api/admin/media",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");onChange([...(value||[]),...(d.items||[])]);}catch(e){setError(e.message)}finally{setBusy(false);e.target.value=""}}
 function remove(i){onChange((value||[]).filter((_,n)=>n!==i))}
 return <div className="space-y-3"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 px-4 py-7 text-sm font-semibold text-slate-600 hover:border-indigo-300 hover:bg-indigo-50"><input type="file" multiple accept="image/*,video/mp4,video/webm,application/pdf" className="hidden" onChange={upload}/>{busy?<span>Uploading…</span>:<><Upload size={18}/> Upload unlimited property media</>}</label><p className="text-xs text-slate-400">Images, MP4/WebM videos and PDF brochures. Up to 50MB per file. Add as many files as your hosting/storage permits.</p>{error&&<p className="text-xs text-red-600">{error}</p>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{(value||[]).map((m,i)=><div key={`${m.url}-${i}`} className="group relative overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="aspect-video bg-slate-100">{m.type==="video"?<video src={m.url} muted className="h-full w-full object-cover"/>:m.type==="brochure"?<div className="grid h-full place-items-center"><FileText/></div>:<img src={m.url} alt="" className="h-full w-full object-cover"/>}</div><div className="flex items-center justify-between gap-2 p-2 text-[11px]"><span className="truncate">{m.title||m.type}</span><button type="button" onClick={()=>remove(i)} className="shrink-0 text-red-600"><Trash2 size={14}/></button></div>{m.type==="video"&&<Video size={14} className="absolute left-2 top-2 text-white drop-shadow"/>}{m.type==="image"&&<ImagePlus size={14} className="absolute left-2 top-2 text-white drop-shadow"/>}</div>)}</div></div>
}
