"use client";
import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
export default function SellPropertyForm(){
 const [f,setF]=useState({name:"",phone:"",email:"",propertyType:"Apartment",purpose:"Sell",location:"",area:"",areaUnit:"sq.ft",expectedPrice:"",titleStatus:"",message:""}); const [done,setDone]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 async function submit(e){e.preventDefault();setBusy(true);setError("");const message=`SELL/PROPERTY ENQUIRY\nType: ${f.propertyType}\nLocation: ${f.location}\nArea: ${f.area} ${f.areaUnit}\nExpected price: ${f.expectedPrice}\nTitle/ownership status: ${f.titleStatus}\nDetails: ${f.message}`;try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.name,phone:f.phone,email:f.email,message,source:"Sell property"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to send");setDone(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(done)return <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={46}/><h2 className="mt-4 text-2xl font-semibold">Request received</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-emerald-900/70">Our property team will review your details and contact you to understand the property, documents and next steps.</p></div>;
 const input="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-indigo-500";
 return <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Your name *<input required minLength={2} className={input+" mt-1"} value={f.name} onChange={e=>set("name",e.target.value)}/></label><label className="text-sm font-medium">Phone number *<input required minLength={7} className={input+" mt-1"} value={f.phone} onChange={e=>set("phone",e.target.value)}/></label><label className="text-sm font-medium">Email<input type="email" className={input+" mt-1"} value={f.email} onChange={e=>set("email",e.target.value)}/></label><label className="text-sm font-medium">Property type<select className={input+" mt-1"} value={f.propertyType} onChange={e=>set("propertyType",e.target.value)}>{["Apartment","Villa","Plot","Land","Office","Shop","Showroom","Warehouse","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Location / locality *<input required className={input+" mt-1"} value={f.location} onChange={e=>set("location",e.target.value)}/></label><label className="text-sm font-medium">Area<input className={input+" mt-1"} value={f.area} onChange={e=>set("area",e.target.value)} placeholder="e.g. 1200"/></label><label className="text-sm font-medium">Area unit<select className={input+" mt-1"} value={f.areaUnit} onChange={e=>set("areaUnit",e.target.value)}><option>sq.ft</option><option>sq.m</option><option>acre</option><option>guntha</option><option>hectare</option></select></label><label className="text-sm font-medium">Expected price<input className={input+" mt-1"} value={f.expectedPrice} onChange={e=>set("expectedPrice",e.target.value)} placeholder="e.g. ₹1.2 Cr"/></label><label className="text-sm font-medium md:col-span-2">Ownership / title status<input className={input+" mt-1"} value={f.titleStatus} onChange={e=>set("titleStatus",e.target.value)} placeholder="e.g. Clear title, single owner, documents available"/></label><label className="text-sm font-medium md:col-span-2">Tell us more<textarea rows={5} className={input+" mt-1"} value={f.message} onChange={e=>set("message",e.target.value)} placeholder="Property condition, floor, furnishing, road access, documents, preferred timeline, etc."/></label></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={busy} className="mt-5 w-full rounded-xl bg-[#151a3a] px-5 py-3.5 text-sm font-semibold text-white hover:bg-indigo-800 disabled:opacity-60">{busy?"Sending…":"Submit property details"}</button><p className="mt-3 text-center text-xs text-slate-400">Please do not share sensitive financial or identity documents in this form.</p></form>
}
