"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { LockKeyhole, ArrowLeft } from "lucide-react";
export default function AdminLoginPage() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(""); try { const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Login failed"); router.replace("/admin/dashboard"); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main data-admin-page="true" className="min-h-screen bg-[#f6f8fc] px-4 py-12 flex items-center justify-center"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/> Back to website</Link><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#151a3a] text-white"><LockKeyhole size={25}/></div><p className="text-xs font-bold uppercase tracking-[.22em] text-indigo-600">Butterfly Homes</p><h1 className="mt-2 text-3xl font-semibold text-slate-900">Admin sign in</h1><p className="mt-2 text-sm leading-6 text-slate-500">Sign in to manage properties, website content and enquiries.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-medium text-slate-700">Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500"/></label><label className="block text-sm font-medium text-slate-700">Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500"/></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-[#151a3a] px-4 py-3.5 font-semibold text-white hover:bg-indigo-800 disabled:opacity-60">{busy?"Signing in…":"Sign in securely"}</button></form><p className="mt-5 text-xs leading-5 text-slate-400">Admin access is configured through private server environment variables. Do not share admin credentials.</p></div></main>;
}
