import mongoose from "mongoose";
const SiteSettingsSchema = new mongoose.Schema({
  key: { type: String, unique: true, default: "global" },
  siteName: { type: String, default: "Butterfly Homes" },
  tagline: { type: String, default: "Find a place that feels like home." },
  heroTitle: { type: String, default: "Find a place that feels like home." },
  heroDescription: { type: String, default: "Discover thoughtfully selected homes, premium residences and exceptional spaces." },
  heroImage: { type: String, default: "/hero-home.jpg" },
  phone: { type: String, default: "" },
  whatsapp: { type: String, default: "" },
  email: { type: String, default: "" },
  address: { type: String, default: "" },
  instagram: { type: String, default: "" },
  facebook: { type: String, default: "" },
  footerText: { type: String, default: "Helping you find a place to belong." },
  aboutTitle: { type: String, default: "A better way to find your place." },
  aboutBody: { type: String, default: "Butterfly Homes helps people discover homes, investment properties and commercial spaces with clarity and confidence." },
  seoTitle: { type: String, default: "Butterfly Homes | Real Estate" },
  seoDescription: { type: String, default: "Discover homes, resale properties, land and commercial real estate with Butterfly Homes." },
  founderName: { type: String, default: "" },
  founderRole: { type: String, default: "Founder" },
  founderBio: { type: String, default: "" },
  founderImage: { type: String, default: "" },
  founderLinkedIn: { type: String, default: "" },
  officeHours: { type: String, default: "" },
  googleBusinessUrl: { type: String, default: "" },
  serviceAreas: { type: String, default: "" },
  organizationDescription: { type: String, default: "" },
  defaultOgImage: { type: String, default: "/hero-home.jpg" },
  canonicalBaseUrl: { type: String, default: "" },
  footerNote: { type: String, default: "" },
}, { timestamps: true });
export default mongoose.models.SiteSettings || mongoose.model("SiteSettings", SiteSettingsSchema);
